//Localhost

###All Chars
GET http://localhost:3000/characters

###Add a Char
POST http://localhost:3000/characters 
Content-Type: application/json

{
      "firstname": "Flush",
      "lastname": "Me",
      "series": ["Nowhere"],
      "homeland": "Um",
      "currentHome": "Gone",
      "species": "Missing",
      "hairColor": "Last",
      "eyeColor": "Week",
      "favColor": "THe big red x",
      "age": 0,
      "siblings": ["Oh noes", "Leave us"]
    }

### Get One Char
GET http://localhost:3000/characters/6333b7674aa3c30d33c54d7c


### Update Char
PUT http://localhost:3000/characters/633761b0bfc51410ee06582f
Content-Type: application/json

# {
#   "firstname": "Samwise",
#   "lastname": "Gamgee",
#   "series": [
#     "The Lord of the Rings"
#   ],
#   "homeland": "The Shire",
#   "currentHome": "The Shire",
#   "species": "Hobbit",
#   "hairColor": "dirty blonde",
#   "eyeColor": "brown",
#   "favColor": "green",
#   "age": 50,
#   "siblings": []
#     }

{"firstname": "Amberle",
    "lastname": "Elessedil",
    "series": [
      "The Elfstones of Shannara"
    ],
    "homeland": "Arborlon",
    "currentHome": "Arborlon",
    "species": "Elf",
    "hairColor": "chestnut",
    "eyeColor": "green",
    "favColor": "orange",
    "age": 18,
    "siblings": []}

### Delete Char
DELETE  http://localhost:3000/characters/633763d56ae9e6e903641678

//Quotes
### All Quotes
GET http://localhost:3000/quotes

###Add a Quote
POST http://localhost:3000/quotes
Content-Type: application/json

 {
  "_id": "6333b7aa5b1ea23036c26897",
  "quote": "Delete this quote",
  "author": "Please Remove",
  "loc": "Get off my dirt"
  }

### Get One Quote
GET http://localhost:3000/quotes/633528542609e4932f66e5e0

### Update a Quote
PUT http://localhost:3000/quotes/633528542609e4932f66e5e0
Content-Type: application/json

 {
    "_id": "6333b7aa5b1ea23036c26897",
    "quote": "Maybe the paths we each shall tread are already laid before our feet though we do not see them.",
    "author": "Galadriel",
    "loc": "Lothlorien, Fellowship of the Ring"
  }

### Delete a Quote
DELETE  http://localhost:3000/quotes/6336011008a0e23769dea90c

//Render
###All Chars
GET https://tauriel341-project2.onrender.com/characters

###Add a Char
POST http://tauriel341-project2.onrender.com/characters 
Content-Type: application/json

{
      "firstname": "Tauriel",
      "lastname": "Greenleaf",
      "series": "Middle Earth",
      "homeland": "Mirkwood",
      "currentHome": "Mirkwood",
      "species": "Elf",
      "hairColor": "red",
      "eyeColor": "green",
      "favColor": "forest green",
      "age": { "$numberInt": "600" },
      "siblings": []
    }

### Get One Char
GET http://tauriel341-project2.onrender.com/characters/6333c354481a3942fe570294


### Update Char
PUT http://tauriel341-project2.onrender.com/characters/6333c354481a3942fe570294
Content-Type: application/json

{
  "firstname": "Mæthóriel",
  "lastname": "Noraskosen",
  "series": [
    "The Sibling Bond"
  ],
  "homeland": "Taurenor, Alvena",
  "currentHome": "Taurenor, Alvena",
  "species": "Elf",
  "hairColor": "blonde",
  "eyeColor": "blue",
  "favColor": "pink",
  "age": {
    "$numberInt": "2020"
  },
  "siblings": [
    "Amerond",
    "Næsalia",
    "Elethial"
  ]
    }

### Delete Char
DELETE  http://tauriel341-project2.onrender.com/characters/633528152609e4932f66e5df

//Quotes
### All Quotes
GET http://tauriel341-project2.onrender.com/quotes

###Add a Quote
POST http://tauriel341-project2.onrender.com/quotes
Content-Type: application/json

 {
  "_id": "6333b7aa5b1ea23036c26897",
  "quote": "Delete this quote",
  "author": "Please Remove",
  "loc": "Get off my dirt"
  }

### Get One Quote
GET http://tauriel341-project2.onrender.com/quotes/6336011008a0e23769dea90c

### Update a Quote
PUT http://tauriel341-project2.onrender.com/quotes/6333b7aa5b1ea23036c26897
Content-Type: application/json

 {
    "_id": "6333b7aa5b1ea23036c26897",
    "quote": "Maybe the paths we each shall tread are already laid before our feet though we do not see them.",
    "author": "Galadriel",
    "loc": "Lothlorien, Fellowship of the Ring"
  }

### Delete a Quote
DELETE  http://tauriel341-project2.onrender.com/quotes/6336011008a0e23769dea90c
